### PR TITLE
35 change lexing sequence

### LINKED ISSUE #35: Change Lexing sequence
Right now the input string gets
1. tokenized
2. expanded + quote removed

This can lead to a bug, if the expanded variable is a command + arg, e.g. test="ls -la". 
In this case the tokenizer doesn't recognize the token, since it's not expanded yet. This is a problem for execve, which needs it's args neatly cut.

Simply swapping tokenize and expand+quotes also doesn't work. It could cut up a previously quoted string.

A possible solution could be expand > tokenize > quote removal. Therefore expand+quotes function needs to be split.

### PR DESCRIPTION
**Pull request by gwolf-011235**
#### New type in token list

Lexer also checks for Assignment (type: ASSIGN). This is true if the string (1) starts with alpha or underscore, (2) continues with alpha, underscore or numeric, (3) ends with '='

#### New expand sequence

ft_expand_tkn_list() now checks for different types and handles them accordingly
- Heredoc (<<): jump over node and perform quote removal
- Redirect (<, >, >>): jump over node and expand vars and quote removal. Set type to AMBIGUOUS if no filename remains (except if it was quoted) 
- Assign: expand vars and quote removal. Sets type to ARG at the end
- Arg: expand, field split and quote removal. Assigns type DELETE if nothing remains (and not quoted). Deletes all DELETE node at the end.
- t_track struct is used to track stuff regarding the current list->content

#### Buffer

Buffer gets own file with dedicated functions. Just a baseline, still needs to be implemented fully.

#### Tkn_list

Refactored tkn_list into it's own files, since lexer and expander use it, and it now has many dedicated functions for create, search and delete

#### Promt /h

Prompt for hostname now checks in /proc/sys/kernel/hostname for the hostname

### CODE REVIEW

File: inc/minishell_error.h [hunk 1]
```diff
@@ -53,8 +53,9 @@ typedef enum e_error {
 	ERR_FORK, ///< Failure to fork.
 	ERR_DUPL, ///< Error while duplicating file descriptor.
 	ERR_EXECVE, ///< Execve encountered an error.
-	ERR_WAIT ///< Error while waiting for exit status of child process.
+	ERR_WAIT, ///< Error while waiting for exit status of child process.
+	ERR_NOSPLIT, ///< ft_field_split() didnt split.
+	ERR_OPEN ///< open() failed.
```
Comment (u413-284-si) [inline inc/minishell_error.h:57]: Double error declaration for same case. Needs solution

File: inc/mod_expand.h [hunk 2]
```diff
@@ -34,24 +36,57 @@ typedef struct s_str_info {
  * @brief Tracker struct.
  *
  * Track current position of input string.
- *
  * @param str Pointer to string.
  * @param pos Current position of the input string.
```
Comment (u413-284-si) [inline inc/mod_expand.h:40]: Doxygen needs to be updated

File: inc/mod_expand.h [hunk 3]
```diff
@@ -34,24 +36,57 @@ typedef struct s_str_info {
...
+t_err	ft_rm_single_quote(t_track *input);
+t_err	ft_rm_double_quote(t_track *input);
+
+//expand_utils.c
+t_err	ft_init_tracker(t_track *input, char *str);
+t_err	ft_move_tracker(t_track *input);
+t_err	ft_eat_char(t_track *input);
+t_err	ft_insert_replace(t_track *input, t_str token, t_str replace);
 
 #endif
```
Comment (u413-284-si) [inline inc/mod_expand.h]: nwl at eof missing

File: inc/tkn_list.h [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+/**
+ * @brief Enum of different types that can be assigned to tokens
+ *
+ * @param ARG		Any string that is not connected to redirects, piping or newlines.
+ * @param INFILE	Redirect evoking an infile.
+ * @param HEREDOC	Redirect evoking a heredoc.
+ * @param OUTFILE	Redirect evoking an outfile.
+ * @param APPEND	Redirect evoking an outfile in append mode.
+ * @param PIPE		Char indicating piping of commands.
+ * @param Newline	Char indicating end of a command.
```
Comment (u413-284-si) [inline inc/tkn_list.h]: doxygen not updated.

File: src/expand.c [hunk 5]
```diff
@@ -5,147 +5,125 @@
...
+			err = ft_expand_heredoc(&tmp);
+		else if (tmp->type == ASSIGN)
+			err = ft_expand_assign(&tmp, env_table);
+		else if (tmp->type == PIPE || tmp->type == NEWL)
+			err = SUCCESS;
+		else
+			err = ft_expand_arg(&tmp, env_table);
+		if (err != SUCCESS)
+			return (err);
+		if (tmp == NULL || tmp->next == NULL)
```
Comment (u413-284-si) [inline src/expand.c]: Do we require to check for tmp == NULL?

File: src/expand.c [hunk 6]
```diff
@@ -5,147 +5,125 @@
...
+	*list = (*list)->next;
+	ft_init_tracker(&input, (*list)->content);
+	while (input.str[input.pos])
+	{
+		if (input.str[input.pos] == '\'' && !input.quoted)
+			err = ft_rm_single_quote(&input);
+		else if (input.str[input.pos] == '"')
+			err = ft_rm_double_quote(&input);
+		else
+			err = ft_move_tracker(&input);
```
Comment (u413-284-si) [inline src/expand.c]: sus

File: src/expand.c
Comment (u413-284-si) [inline src/expand.c:1]: Doxygen missing

File: src/expand.c [hunk 7]
```diff
@@ -5,147 +5,125 @@
...
-		else if (input.str[input.pos] == '$')
-			err = ft_expand_var(&input, symtab, info, in_double_quotes);
-		else
-			input.pos++;
-		if (err != SUCCESS && err != ERR_NOEXPAND)
+		err = ft_expander_arg(&input, symtab);
+		if (err != SUCCESS)
 			return (err);
+		(*list)->content = input.str;
+		if (input.last_expand_len > 0 && !input.quoted && input.expanded)
```
Comment (u413-284-si) [inline src/expand.c]: input.last_expand_len > 0 and input.expanded fulfill the same purpose? We don't require the boolean

File: src/expand_expander.c [hunk 8]
```diff
@@ -0,0 +1,79 @@
...
+{
+	t_err	err;
+
+	while (input->str[input->pos])
+	{
+		if (input->str[input->pos] == '\'' && !input->quoted)
+			err = ft_rm_single_quote(input);
+		else if (input->str[input->pos] == '"')
+			err = ft_rm_double_quote(input);
+		else if (input->pos == 0 && input->str[input->pos] == '~')
```
Comment (u413-284-si) [inline src/expand_expander.c]: ft_expand_tilde() needs to be called also in the middle of the input str

File: src/expand_expander.c [hunk 9]
```diff
@@ -0,0 +1,79 @@
...
+/*   Updated: 2023/08/10 11:58:54 by gwolf            ###   ########.fr       */
+/*                                                                            */
+/* ************************************************************************** */
+
+/**
+ * @file expand.c
+ * @brief Contains driver function to handle expansion and quote removal.
+ */
+#include "mod_expand.h"
+
```
Comment (u413-284-si) [inline src/expand_expander.c:18]: Doxygen missing

File: src/expand_expander.c [hunk 10]
```diff
@@ -0,0 +1,79 @@
...
+ *
+ * Go through the string and check for special chars.
+ * Tilde: ft_expand_tilde().
+ * $: ft_expand_var().
+ * Single quote: ft_skip_single_quote().
+ * Double quote: ft_skip_double_quote().
+ *
+ * @param expr The expression to be expanded.
+ * @param symtab The environment table
+ * @param info Data for return code and shell name.
```
Comment (u413-284-si) [inline src/expand_expander.c]: Not up to date

File: src/expand_field_split.c [hunk 11]
```diff
@@ -0,0 +1,197 @@
...
+		err = ft_tokenise_fs(&src, &token, buf, input);
+	}
+	return (SUCCESS);
+}
+
+/**
+ * @brief Tokenise a string while field split.
+ *
+ * Based on ft_tokenise().
+ * Uses partition_two() to fill buffer.
```
Comment (u413-284-si) [inline src/expand_field_split.c]: update doxygen

File: src/expand_quote_removal.c [hunk 12]
```diff
@@ -0,0 +1,80 @@
...
+	ft_init_tracker(&input, str);
+	while (input.str[input.pos])
+	{
+		if (input.str[input.pos] == '\'' && !input.quoted)
+			err = ft_rm_single_quote(&input);
+		else if (input.str[input.pos] == '"')
+			err = ft_rm_double_quote(&input);
+		else
+			err = ft_move_tracker(&input);
+		if (err != SUCCESS)
```
Comment (u413-284-si) [inline src/expand_quote_removal.c]: Superfluous, the called functions all return only SUCCESS

File: src/expand_field_split.c (hunk 11 above)
Comment (u413-284-si) [reply src/expand_field_split.c]: Elaborate on action in if (src->cur_pos == src->buf_size && input->str[input->pos])

File: src/expand_tilde.c [hunk 13]
```diff
@@ -6,55 +6,51 @@
...
-		return (ERR_NOT_FOUND);
-	}
-	replace->ptr = ft_strdup(env_var->value);
-	if (!replace->ptr)
-		return (ERR_MALLOC);
-	replace->len = ft_strlen(replace->ptr);
+	if (input->pos != 0 && input->str[input->pos - 1] != '=')
+		return (ERR_NOEXPAND);
+	token.ptr = NULL;
+	err = ft_get_tilde_token(input, &token);
```
Comment (u413-284-si) [inline src/expand_tilde.c]: Suggest to replace ft_get_tilde_token with ft_get_tilde_var to avoid confusion with the tokens used in the program

File: src/expand_tilde.c [hunk 14]
```diff
@@ -64,11 +60,9 @@ t_err	ft_get_tilde_replace(t_str token, t_hashtable *symtab, t_str *replace, siz
...
  * If '+' or '-' is found increase position and reassign
  * Then a '/' or a '\0' has to be found, else the string is set to NULL.
- * Also if not found increase the position to jump over the '~'.
+ * Also if not found increase tracker position to jump over the '~'.
  * Calc the token.len.
- *
- * @param input String.
- * @param pos Current position.
+ * @param input Pointer to tracker.
  * @param token Where to save the token.
```
Comment (u413-284-si) [inline src/expand_tilde.c]: token -> variable

File: src/expand_tilde.c [hunk 15]
```diff
@@ -96,41 +90,42 @@ t_err	ft_get_tilde_token(t_track *input, t_str *token)
...
- * @param input String.
+ * Depending on the token find env var.
+ * ~ = $HOME.
+ * ~+ = $PWD.
+ * ~- = $OLDPWD.
+ * If not found increase tracker position to account for '~' and
+ * return ERR_NOT_FOUND.
+ * If found ft_strdup() the value.
+ * Calc replace.len.
+ * @param token Contains searched for token.
```
Comment (u413-284-si) [inline src/expand_tilde.c]: token -> variable

File: src/expand_utils.c [hunk 16]
```diff
@@ -0,0 +1,101 @@
...
+	input->expanded = false;
+	input->last_expand_len = 0;
+	input->found_quote = false;
+	return (SUCCESS);
+}
+
+/**
+ * @brief Move tracker forward by one.
+ *
+ * Function only needed because of norminette.
```
Comment (u413-284-si) [inline src/expand_utils.c]: Comments do not need to justify function

File: src/expand_utils.c [hunk 17]
```diff
@@ -0,0 +1,101 @@
...
+ * @param input Pointer to tracker.
+ * @return t_err SUCCESS
+ */
+t_err	ft_move_tracker(t_track *input)
```
Comment (u413-284-si) [inline src/expand_utils.c:42]: Greatest function ever

File: src/expand_var.c [hunk 18]
```diff
@@ -17,26 +17,56 @@
...
+		free (replace.ptr);
+	input->pos += replace.len;
+	input->last_expand_len = replace.len;
+	if (err == SUCCESS)
+		input->expanded = true;
+	return (err);
+}
+
+/**
+ * @brief Handle the special variable $?
```
Comment (u413-284-si) [inline src/expand_var.c]: Would describe shortly what $? does

File: src/tkn_list_search.c [hunk 19]
```diff
@@ -0,0 +1,54 @@
...
+ * @file tkn_list_search.c
+ * @brief Search for specific nodes.
+ */
+#include "tkn_list.h"
+
+/**
+ * @brief Iterate to first node of given list.
+ *
+ * @param lst Pointer pointer to a list node.
+ * @return t_err SUCCESS.
```
Comment (u413-284-si) [inline src/tkn_list_search.c]: oida!

Comment (u413-284-si) [reply src/tkn_list_search.c]: doxygen is not representing the truth

**Review by u413-284-si — CHANGES_REQUESTED** [review]

**Comment by u413-284-si** [comment]
Good work! Handling all the special cases while expanding variables is difficult feat. Kudos to that! 

Mostly documentation issues which was not up to date or could be more specific. But as we already agreed on, the finalisation of the doxygen documentation shall be effected after the program is standing and error prone. 

Some dead code/unnecessary code which can be omitted.

File: inc/minishell_error.h (hunk 1 above)
Comment (gwolf-011235) [reply inc/minishell_error.h:57]: I suggest deleting the error ERR_BAD_FD.

It's complementary errno would be EBADF, which is described as: Bad file descriptor; for example, I/O on a descriptor that has been closed or reading from a descriptor open only for writing (or vice versa). 

So a bad file descriptor is a valid file descriptor (which wikipedia says typically have non-negative integer values). Just the operation done on it is wrong.

Right now the error ERR_BAD_FD is used if the open() call fails, which does return -1. But this implies that no file descriptor was assigned.

Comment (u413-284-si) [reply inc/minishell_error.h:57]: Open to delete ERR_BAD_FD and replace its occurences with ERR_OPEN

File: inc/mod_expand.h (hunk 2 above)
Comment (gwolf-011235) [reply inc/mod_expand.h:40]: Updated

File: inc/mod_expand.h (hunk 3 above)
Comment (gwolf-011235) [reply inc/mod_expand.h]: Updated

File: inc/tkn_list.h (hunk 4 above)
Comment (gwolf-011235) [reply inc/tkn_list.h]: Done

File: src/expand.c (hunk 5 above)
Comment (gwolf-011235) [reply src/expand.c]: I don't think so. Removed.

File: src/expand_tilde.c (hunk 15 above)
Comment (gwolf-011235) [reply src/expand_tilde.c]: Changed token to var

File: src/expand_utils.c (hunk 16 above)
Comment (gwolf-011235) [reply src/expand_utils.c]: I was just hurt and needed to vent :cry: 
Removed

File: src/expand_utils.c (hunk 17 above)
Comment (gwolf-011235) [reply src/expand_utils.c:42]: True

File: src/expand_var.c (hunk 18 above)
Comment (gwolf-011235) [reply src/expand_var.c]: Added explainer

File: src/tkn_list_search.c (hunk 19 above)
Comment (gwolf-011235) [reply src/tkn_list_search.c]: Updated

File: inc/minishell_error.h (hunk 1 above)
Comment (gwolf-011235) [reply inc/minishell_error.h:57]: Replaced occurences with ERR_OPEN

File: src/expand.c (hunk 6 above)
Comment (gwolf-011235) [reply src/expand.c]: Bruh

File: src/expand_utils.c (hunk 16 above)
Comment (u413-284-si) [reply src/expand_utils.c]: relatable

File: src/expand.c
Comment (gwolf-011235) [reply src/expand.c:1]: Added doxy

File: src/expand.c (hunk 7 above)
Comment (gwolf-011235) [reply src/expand.c]: True! Removed bool and only check with last_expand_len

File: src/expand.c (hunk 6 above)
Comment (u413-284-si) [reply src/expand.c]: hombre

File: src/expand_expander.c (hunk 8 above)
Comment (gwolf-011235) [reply src/expand_expander.c]: True. Refactored both expander fts into one and implemented special

File: src/expand_expander.c (hunk 9 above)
Comment (gwolf-011235) [reply src/expand_expander.c:18]: Added doxy

File: src/expand_expander.c (hunk 10 above)
Comment (gwolf-011235) [reply src/expand_expander.c]: Updated

File: src/expand_field_split.c (hunk 11 above)
Comment (gwolf-011235) [reply src/expand_field_split.c]: Added elaboration

File: src/expand_quote_removal.c (hunk 12 above)
Comment (gwolf-011235) [reply src/expand_quote_removal.c]: Removed return value of ft_quote_removal()

File: src/expand_tilde.c (hunk 13 above)
Comment (gwolf-011235) [reply src/expand_tilde.c]: Done

File: src/expand_tilde.c (hunk 14 above)
Comment (gwolf-011235) [reply src/expand_tilde.c]: Done

File: src/expand_quote_removal.c (hunk 12 above)
Comment (gwolf-011235) [reply src/expand_quote_removal.c]: Update: removed whole functions since nowhere used anymore :D

Comment (gwolf-011235) [reply src/expand_quote_removal.c]: Update2: deleted file expand_quote_removal.c by putting it's functions into the expand_expander.c since this is the main function which calls the quote removal functions.

File: src/expand.c (hunk 6 above)
Comment (gwolf-011235) [reply src/expand.c]: jabroni!
